repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.15
    hooks:
      # Update the uv lockfile
      - id: uv-lock

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=20000']
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
    - id: ruff
      args:
        [
          --fix,
          --exit-non-zero-on-fix,
          --show-fixes
          ]
    - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-pyyaml>=6.0.12.20250516
          - types-requests>=2.32.0.20250602
        args:
          [
            --config-file=pyproject.toml,
            # --ignore-missing-imports
            ]

  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        additional_dependencies:
        - mdformat-gfm
        exclude: ^team_data/


  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.2
    hooks:
      - id: gitleaks
        args: ["--config=.gitleaks.toml"]

  - repo: local
    hooks:
      - id: lint-makefile
        name: Lint Makefile for missing help comments
        entry: scripts/lint-makefile.sh
        language: script
        files: ^Makefile$

  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: pytest
  #       language: system
  #       types: [python]
  #       pass_filenames: false
