"""Initial migration

Revision ID: 3ee816d93186
Revises:
Create Date: 2025-06-22 19:36:53.315554

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "3ee816d93186"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
