"""changed types

Revision ID: b70c19550a8c
Revises: 3f8fd10eb311
Create Date: 2025-06-17 17:14:09.743881

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b70c19550a8c"
down_revision: str | Sequence[str] | None = "3f8fd10eb311"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "comments", "author", existing_type=sa.VARCHAR(length=100), type_=sa.String(length=120), existing_nullable=True
    )
    op.alter_column(
        "issues", "state", existing_type=sa.VARCHAR(length=20), type_=sa.String(length=30), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "issues", "state", existing_type=sa.String(length=30), type_=sa.VARCHAR(length=20), existing_nullable=True
    )
    op.alter_column(
        "comments", "author", existing_type=sa.String(length=120), type_=sa.VARCHAR(length=100), existing_nullable=True
    )
    # ### end Alembic commands ###
