"""Describe change

Revision ID: d84b3a18383b
Revises:
Create Date: 2025-06-17 21:38:49.100905

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d84b3a18383b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
