apiVersion: v1
kind: Pod
metadata:
  name: rds-test2
  namespace: my-app
  labels:
    app: fastapi
spec:
  containers:
  - name: psql
    image: postgres:alpine
    command: ["sh", "-c", "sleep 3600"]
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "1000m"
